# ==============================================================================================
# Project: PEARL -- PRNG Evaluation for Area, Randomness, and Leakage
# Authors: Valeria Piscopo, Alessandra Dolmeta (EDGE Group, VLSI Lab, Dept. of Electronics and Telecommunications, Politecnico di Torino);
#          Behnam Farnaghinejad (Dept. of Control and Computer Engineering, Politecnico di Torino)
# ----------------------------------------------------------------------------------------------

MODULE_NAME ?= MersenneTwister
MAIN ?= main_SIM.cpp
SRC = $(MAIN) MersenneTwister.cpp ../Common/bytesNumber.cpp ../Common/ParameterParser.cpp

include ../common.mk
