# ==============================================================================================
# Project: PEARL -- PRNG Evaluation for Area, Randomness, and Leakage
# Authors: Valeria Piscopo, Alessandra Dolmeta (EDGE Group, VLSI Lab, Dept. of Electronics and Telecommunications, Politecnico di Torino);
#          Behnam Farnaghinejad (Dept. of Control and Computer Engineering, Politecnico di Torino)
# ----------------------------------------------------------------------------------------------

MODULE_NAME ?= ctr_drbg
MAIN ?= main.cpp
SRC = $(MAIN) ../Common/bytesNumber.cpp ../Common/ParameterParser.cpp ../Common/BlockFunction.cpp ../AES_128/AESBlockFunction.cpp ../Keccak/Keccak.cpp ctr_drbg.cpp

include ../common.mk
