# ==============================================================================================
# Project: PEARL -- PRNG Evaluation for Area, Randomness, and Leakage
# Authors: Valeria Piscopo, Alessandra Dolmeta (EDGE Group, VLSI Lab, Dept. of Electronics and Telecommunications, Politecnico di Torino);
#          Behnam Farnaghinejad (Dept. of Control and Computer Engineering, Politecnico di Torino)
# ----------------------------------------------------------------------------------------------

MODULE_NAME ?= AES_128
MAIN ?= main.cpp
SRC = $(MAIN) AESBlockFunction.cpp ../Common/BlockFunction.cpp ../Common/bytesNumber.cpp

include ../common.mk
