#!/usr/bin/env bash

# ==============================================================================================
# Project: PEARL -- PRNG Evaluation for Area, Randomness, and Leakage
# Authors: Valeria Piscopo, Alessandra Dolmeta (EDGE Group, VLSI Lab, Dept. of Electronics and Telecommunications, Politecnico di Torino);
#          Behnam Farnaghinejad (Dept. of Control and Computer Engineering, Politecnico di Torino)
# ----------------------------------------------------------------------------------------------

if [[ -v PROJECT_STRUCTURE_LOADED ]]; then
	return 0
fi
readonly PROJECT_STRUCTURE_LOADED=1

: "${MODULE_NAME:=NOT_SET}"
: "${VARIANT_NAME:=default}"

# Define folders and file names used in the script
declare -rx SCRIPT_FOLDER="$PROJECT_ROOT/scripts"											# Folder containing the project scripts
declare -rx UTILITY_SCRIPT_FOLDER="$SCRIPT_FOLDER/utility_scripts"							# Folder containing utility scripts
declare -rx CONFIG_DIR="$SCRIPT_FOLDER/config"												#
declare -rx CONFIG_TARGETS="$CONFIG_DIR/targets.json"							#
declare -rx DEFAULT_SERVER_BASE_FOLDER="SpecialProject"										#
declare -rx PRJ_FOLDER="$PROJECT_ROOT/prj"													# Folder contianning the .prj file containing all SystemVerilog file paths to all modules needed for the MODULE_NAME simulation

# Simulation folders and files
declare -rx SIM_FOLDER="$PROJECT_ROOT/sim/${MODULE_NAME}/${VARIANT_NAME}"					# Main folder for simulation (using Verilator)
declare -rx SIM_LOG_FOLDER="$SIM_FOLDER/logs"												# Folder where simulation logs are stored
declare -rx SIM_REPORT_FOLDER="$SIM_FOLDER/reports"											# Folder where simulation summary reports are stored
declare -rx VECTOR_FOLDER="$SIM_FOLDER/vectors"												# Folder for input/output vector files are stored, from GoldenModel and Verilator simulation
declare -rx BUILD_FOLDER="$SIM_FOLDER/build"												# Folder for Verilator executable will be built
declare -rx EXEC_FOLDER="$SIM_FOLDER/executables"											# Folder for GoldenModel (and possibly other programs used for simulation) executable will be stored
declare -rx SIM_SCRIPT_LOG="$SIM_LOG_FOLDER/SIM_${MODULE_NAME}.log"							# File where the simulation script terminal dump is stored
declare -rx SIM_GOLDENMODEL_LOG="$SIM_LOG_FOLDER/goldenModel_${MODULE_NAME}.log"			# File where the simulation Golden Model build log is stored
declare -rx SIM_VERILATOR_LOG="$SIM_LOG_FOLDER/verilator_${MODULE_NAME}.log"				# File where the Verilator build log is stored
declare -rx SIM_PERFORMANCE_FILE="$SIM_REPORT_FOLDER/performance.csv"						# CSV file containing simulation performance counters
declare -rx VCD_FILE="$SIM_LOG_FOLDER/${MODULE_NAME}.vcd"									# VCD file generated by the Verilator simulation

# Source folders
declare -rx RTL_FOLDER="$PROJECT_ROOT/rtl"													# 
declare -rx TB_FOLDER="$PROJECT_ROOT/tb"													# 
declare -rx KECCAK_RTL_FOLDER="$PROJECT_ROOT/keccak/src/rtl"								# Keccak RTL folder used by DP
declare -rx KECCAK_RTL_SERVER_REL="keccak/src/rtl"										# Relative path expected by the .prj files

# Synthesis folders and files
declare -rx SYNTH_FOLDER="$PROJECT_ROOT/synth"												# Folder containing generated synthesis outputs
declare -rx SYNTH_PLOT_FOLDER="$SYNTH_FOLDER/plots"										# Folder for plots generated from synthesis summaries
declare -rx SYNTH_SCRIPT_FOLDER="$SCRIPT_FOLDER/synth"										# Folder containing synthesis flow scripts
declare -rx SYNTH_ASIC_SCRIPTS_FOLDER="$SYNTH_SCRIPT_FOLDER/ASIC"							# Folder containing ASIC synthesis flow scripts
declare -rx SYNTH_ASIC_RESULT_FOLDER="$SYNTH_FOLDER/${MODULE_NAME}/${VARIANT_NAME}/ASIC"	#
declare -rx SYNTH_ASIC_LOG_FOLDER="$SYNTH_ASIC_RESULT_FOLDER/logs"							#
declare -rx SYNTH_ASIC_NETLIST_FOLDER="$SYNTH_ASIC_RESULT_FOLDER/netlist"					#
declare -rx SYNTH_ASIC_REPORT_FOLDER="$SYNTH_ASIC_RESULT_FOLDER/reports"					#
declare -rx SYNTH_ASIC_WORK_FOLDER="$SYNTH_ASIC_RESULT_FOLDER/work"						#
declare -rx SYNTH_FPGA_SCRIPTS_FOLDER="$SYNTH_SCRIPT_FOLDER/FPGA"							# Folder containing FPGA synthesis flow scripts
declare -rx SYNTH_FPGA_RESULT_FOLDER="$SYNTH_FOLDER/${MODULE_NAME}/${VARIANT_NAME}/FPGA"	#
declare -rx SYNTH_FPGA_LOGS_FOLDER="$SYNTH_FPGA_RESULT_FOLDER/logs"						#
declare -rx SYNTH_FPGA_NETLIST_FOLDER="$SYNTH_FPGA_RESULT_FOLDER/netlist"					#
declare -rx SYNTH_FPGA_REPORTS_FOLDER="$SYNTH_FPGA_RESULT_FOLDER/reports"					#
declare -rx SYNTH_FPGA_WORK_FOLDER="$SYNTH_FPGA_RESULT_FOLDER/work"						#
declare -rx LOG_SYNTH_ASIC="$SYNTH_ASIC_LOG_FOLDER/synth_log.log"							#
declare -rx LOG_SYNTH_FPGA="$SYNTH_FPGA_LOGS_FOLDER/synth_log.log"							#
declare -rx JOURNAL_SYNTH_FPGA="$SYNTH_FPGA_LOGS_FOLDER/vivado.jou"						#
declare -rx STDOUT_SYNTH_FPGA="$SYNTH_FPGA_LOGS_FOLDER/vivado_stdout.log"					#
declare -rx GOLDEN_MODEL_FOLDER="$PROJECT_ROOT/golden_model"								#
declare -rx GOLDEN_FOLDER="$GOLDEN_MODEL_FOLDER/${MODULE_NAME}"							# Folder for Golden Model source code is stored
declare -rx GOLDEN_SIM_MAIN="main_SIM.cpp"													# Main source file used to compile the Golden Model for simulation
declare -rx GOLDEN_NIST_MAIN="main_NIST.cpp"												# Main source file used to compile the Golden Model for NIST tests
declare -rx GOLDEN_SIM_SRC="$GOLDEN_FOLDER/$GOLDEN_SIM_MAIN"								# Full path of the simulation Golden Model main source file
declare -rx GOLDEN_NIST_SRC="$GOLDEN_FOLDER/$GOLDEN_NIST_MAIN"								# Full path of the NIST Golden Model main source file
declare -rx PRJ_FILE_SIM="$PRJ_FOLDER/${MODULE_NAME}_SIM.prj"								# File containing the list of all SystemVerilog files needed for the simulation (contains the paths to TB files)
declare -rx PRJ_FILE_SYNTH_ASIC="$PRJ_FOLDER/${MODULE_NAME}_SYNTH_ASIC.prj"					# File containing the list of SystemVerilog files needed for ASIC synthesis
declare -rx PRJ_FILE_SYNTH_FPGA="$PRJ_FOLDER/${MODULE_NAME}_SYNTH_FPGA.prj"					# File containing the list of SystemVerilog files needed for FPGA synthesis
declare -rx TOP_SYNTH_FPGA="xilinx_${MODULE_NAME}_wrapper"									# FPGA top module name used by Vivado
declare -rx ABS_PRJ_FILE="$BUILD_FOLDER/${MODULE_NAME}_abs.prj"								# File containing the list of all SystemVerilog files needed for the simulation in absolute path format
declare -rx TMP_ABS_PRJ_FILE="$BUILD_FOLDER/${MODULE_NAME}_abs.prj.tmp"						# Temporary file used to update ABS_PRJ_FILE only when content changes
declare -rx GOLDEN_MAKEFILE="$GOLDEN_FOLDER/Makefile"										# Makefile used to compile the Golden Model
declare -rx GOLDEN_EXE="$EXEC_FOLDER/goldenModel_${MODULE_NAME}"							# Name of the Golden Model executable 
declare -rx SIM_EXE_NAME="sim_${MODULE_NAME}"												# Name of the Verilator simulation executable
declare -rx SIM_EXE_PATH="$BUILD_FOLDER/$SIM_EXE_NAME"										# Path of the Verilator simulation executable
declare -rx INPUT_VECTOR_FILE="$VECTOR_FOLDER/inputVect.txt"								# Input vector file generated by the Golden Model
declare -rx OUTPUT_VECTOR_FILE="$VECTOR_FOLDER/outputVect_gold.txt"							# Output vector file generated by the Golden Model
declare -rx HDL_OUTPUT_FILE="$VECTOR_FOLDER/outputVect_hdl.txt"								# Output vector file generated by the HDL (Verilator) simulation

# NIST folders and files
declare -rx NIST_Suite_Folder="$PROJECT_ROOT/NIST-Statistical-Test-Suite"					# Main NIST Test Directory
declare -rx NIST_stsFolder="${NIST_Suite_Folder}/sts"										# Folder containing the NIST STS makefile and executable
declare -rx NIST_MyFolder="$PROJECT_ROOT/NIST_test"											# 
declare -rx NIST_testFolder="$NIST_MyFolder/${MODULE_NAME}/${VARIANT_NAME}"					# Folder containing files used by NIST tests for the selected module
declare -rx NIST_execFolder="$NIST_testFolder/executables"									# Folder containing executables generated for NIST tests
declare -rx NIST_logFolder="$NIST_testFolder/logs"											# Folder containing NIST terminal logs
declare -rx NIST_testConfig="$NIST_testFolder/NIST_test_config.txt"							# File containing the answers for the NIST interactive menu
declare -rx NIST_inputFile="$NIST_testFolder/nistInputBits.txt"								# 
declare -rx NIST_resultFolder="$NIST_stsFolder/experiments/AlgorithmTesting"				# Folder containing NIST result reports
declare -rx NIST_finalAnalysisReport="$NIST_resultFolder/finalAnalysisReport.txt"			# Final report generated by the NIST suite
declare -rx NIST_plotFolder="$NIST_testFolder/plots"										# Folder containing plots generated from NIST results
declare -rx NIST_totalPassRatePlot="$NIST_plotFolder/total_pass_rate_by_test.png"			# Plot showing the total pass rate for every NIST test
declare -rx NIST_uniformityPlotFolder="$NIST_plotFolder/uniformity_histograms"				# Folder containing p-value uniformity histograms
declare -rx NIST_uniformitySummaryFile="$NIST_plotFolder/uniformity_summary.csv"			# CSV summary for p-value uniformity checks
declare -rx NIST_passRateSummaryFile="$NIST_plotFolder/pass_rate_summary.csv"				# CSV summary of per-test-type pass rates
declare -rx SCRIPT_NIST_summarizeResults="$UTILITY_SCRIPT_FOLDER/summarize_NIST_results.py"	# Python script used to summarize NIST pass rates
declare -rx NIST_comparisonPlotFolder="$NIST_MyFolder/plots"								# Folder containing NIST comparison plots
declare -rx NIST_comparisonPlot="$NIST_comparisonPlotFolder/NIST_comparison.png"			# Default output base name for NIST comparison plots
declare -rx NIST_buildLog="$NIST_logFolder/nist_build.log"									# Log file for NIST setup/build output
declare -rx NIST_runLog="$NIST_logFolder/nist_run.log"										# Log file for NIST test execution output
declare -rx NIST_plotLog="$NIST_logFolder/nist_plot.log"									# Log file for NIST plot generation output
declare -rx NIST_goldenModelLog="$NIST_logFolder/goldenModel_${MODULE_NAME}.log"			# Log file for NIST Golden Model build output
declare -rx SCRIPT_NIST_setup="${NIST_Suite_Folder}/setup.sh"								# NIST Setup Script
declare -rx SCRIPT_NIST_runTest="${NIST_stsFolder}/assess"									# NIST Test executable
declare -rx SCRIPT_NIST_plotResults="$UTILITY_SCRIPT_FOLDER/plot_NIST_results.py"			# Python script used to plot NIST results
declare -rx SCRIPT_NIST_compareResults="$UTILITY_SCRIPT_FOLDER/compare_NIST_results.py"	# Python script used to compare NIST results
declare -rx SCRIPT_NIST_compare="$SCRIPT_NIST_compareResults"								# Script used to compare NIST results
declare -rx BASH_LIB_FOLDER="$UTILITY_SCRIPT_FOLDER/bash_lib"								# 
declare -rx BASH_LIB_GENERAL="$BASH_LIB_FOLDER/libBash_General.sh"							# 
declare -rx BASH_LIB_SERVER="$BASH_LIB_FOLDER/libBash_Server.sh"							# 
declare -rx BASH_LIB_JSON="$BASH_LIB_FOLDER/libBash_JSON.bash"								#
declare -rx BASH_LIB_PRINT="$BASH_LIB_FOLDER/libBash_Print.sh"								#
declare -rx SERVER_CONFIG_FILE="$CONFIG_DIR/server.local.sh"								#
declare -rx SCRIPT_SERVER_CONFIG="$UTILITY_SCRIPT_FOLDER/setup_server_config.sh"			# 
declare -rx REPORT_SYNTH_ASIC_TIMING="${SYNTH_ASIC_REPORT_FOLDER}/${MODULE_NAME}_timing.rpt"
declare -rx REPORT_SYNTH_ASIC_AREA="${SYNTH_ASIC_REPORT_FOLDER}/${MODULE_NAME}_area.rpt"
declare -rx REPORT_SYNTH_ASIC_SUMMARY="${SYNTH_ASIC_REPORT_FOLDER}/summary.csv"
declare -rx PLOT_SYNTH_ASIC_PARETO="$SYNTH_PLOT_FOLDER/pareto_asic.png"
declare -rx SDF_SYNTH_ASIC="${SYNTH_ASIC_NETLIST_FOLDER}/${MODULE_NAME}.sdf"
declare -rx NETLIST_SYNTH_ASIC="${SYNTH_ASIC_NETLIST_FOLDER}/${MODULE_NAME}.v"
declare -rx SDC_SYNTH_ASIC="${SYNTH_ASIC_NETLIST_FOLDER}/${MODULE_NAME}.sdc"
declare -rx REPORT_SYNTH_FPGA_TIMING="${SYNTH_FPGA_REPORTS_FOLDER}/${MODULE_NAME}_timing.rpt"
declare -rx REPORT_SYNTH_FPGA_UTILIZATION="${SYNTH_FPGA_REPORTS_FOLDER}/${MODULE_NAME}_utilization.rpt"
declare -rx REPORT_SYNTH_FPGA_POWER="${SYNTH_FPGA_REPORTS_FOLDER}/${MODULE_NAME}_power.rpt"
declare -rx REPORT_SYNTH_FPGA_SUMMARY="${SYNTH_FPGA_REPORTS_FOLDER}/summary.csv"
declare -rx PLOT_SYNTH_FPGA_PARETO="$SYNTH_PLOT_FOLDER/pareto_fpga.png"
declare -rx NETLIST_SYNTH_FPGA="${SYNTH_FPGA_NETLIST_FOLDER}/${MODULE_NAME}.v"
declare -rx DCP_SYNTH_FPGA="${SYNTH_FPGA_NETLIST_FOLDER}/${MODULE_NAME}.dcp"
declare -rx FPGA_PART="${FPGA_PART:-xc7a100tcsg324-1}"


# Scripts used by the synthesis process 
declare -rx SCRIPT_RUN_TARGETS="$SCRIPT_FOLDER/run_targets.sh"						#
declare -rx SCRIPT_RUN_SIM="$SCRIPT_FOLDER/run_SIM.sh"										#
declare -rx SCRIPT_RUN_NIST="$SCRIPT_FOLDER/run_NISTTest.sh"								#
declare -rx SCRIPT_RUN_SYNTH_ASIC="$SCRIPT_FOLDER/run_SYNTH_ASIC.sh"						#
declare -rx SCRIPT_RUN_SYNTH_FPGA="$SCRIPT_FOLDER/run_SYNTH_FPGA.sh"						#
declare -rx SCRIPT_PLOT_SYNTH_ASIC_PARETO="$UTILITY_SCRIPT_FOLDER/plot_SYNTH_ASIC_pareto.py"		#
declare -rx SCRIPT_PLOT_SYNTH_FPGA_PARETO="$UTILITY_SCRIPT_FOLDER/plot_SYNTH_FPGA_pareto.py"		#
declare -rx TCL_SYNTH_ASIC_SET_LIBS="$SYNTH_ASIC_SCRIPTS_FOLDER/set_libs.tcl"
declare -rx SCRIPT_RUN_SYNTH_ASIC_SERVER="$SYNTH_ASIC_SCRIPTS_FOLDER/run_ASIC_synth_server.sh"	#
declare -rx TCL_SCRIPT_SYNTH_ASIC="$SYNTH_ASIC_SCRIPTS_FOLDER/run_ASIC_synth_server.tcl"	#
declare -rx DC_SETUP_SYNTH_ASIC="$SYNTH_ASIC_SCRIPTS_FOLDER/.synopsys_dc.setup"
declare -rx SCRIPT_RUN_SYNTH_FPGA_SERVER="$SYNTH_FPGA_SCRIPTS_FOLDER/run_FPGA_synth_server.sh"	#
declare -rx TCL_SCRIPT_SYNTH_FPGA="$SYNTH_FPGA_SCRIPTS_FOLDER/run_FPGA_synth_server.tcl"	#
declare -rx TCL_SYNTH_FPGA_FLOW="$SYNTH_FPGA_SCRIPTS_FOLDER/FPGA.tcl"						#
declare -rx XDC_SYNTH_FPGA_CONSTRAINT="$SYNTH_FPGA_SCRIPTS_FOLDER/constraint.xdc"			#

# ASIC Synthesis Libraries
#
# Default values point at this repository's own reference PDK setup (a
# private submodule wrapping a proprietary foundry library, not included in
# this public repository). To synthesize against your own standard-cell/
# pad/memory library instead, do NOT edit the defaults below: copy
# scripts/config/asic_lib.example.sh to scripts/config/asic_lib.local.sh
# (git-ignored) and set the variables there. See that file, or the "Bring
# Your Own ASIC Library" section of the top README, for details.
if [[ -f "$CONFIG_DIR/asic_lib.local.sh" ]]; then
	source "$CONFIG_DIR/asic_lib.local.sh"
fi

declare -rx CRHEEPTO_WIP_FOLDER="$PROJECT_ROOT/crheepto_wip"
declare -rx LIB_SYNTH_ASIC_CELLS="${LIB_SYNTH_ASIC_CELLS:-$CRHEEPTO_WIP_FOLDER/hw/asic/symlinks/PDK/Front_End/timing_power_noise/CCS/<stdcell_lib>}"
declare -rx LIB_SYNTH_ASIC_PADS="${LIB_SYNTH_ASIC_PADS:-$CRHEEPTO_WIP_FOLDER/hw/asic/symlinks/PDK/Front_End/timing_power_noise/NLDM/<pad_lib>}"
declare -rx LIB_SYNTH_ASIC_MEMORIES="${LIB_SYNTH_ASIC_MEMORIES:-$CRHEEPTO_WIP_FOLDER/hw/asic/symlinks/MEMORIES/DB}"

# Glob patterns used to pick the right corner/view out of each library
# directory (see scripts/synth/ASIC/set_libs.tcl). Defaults match the naming
# convention of this repository's own reference PDK; override alongside the
# paths above if your library names its .db files differently.
declare -rx LIB_SYNTH_ASIC_CELLS_GLOB="${LIB_SYNTH_ASIC_CELLS_GLOB:-*wc_ccs.db}"
declare -rx LIB_SYNTH_ASIC_PADS_GLOB="${LIB_SYNTH_ASIC_PADS_GLOB:-*wcz.db}"
declare -rx LIB_SYNTH_ASIC_MEMORIES_GLOB="${LIB_SYNTH_ASIC_MEMORIES_GLOB:-*ss*1p08*125*.db}"


if [[ -z "${SERVER_PROJECT_ROOT:-}" && -z "${SERVER_BASE_FOLDER:-}" && -f "$SERVER_CONFIG_FILE" ]]; then
	source "$SERVER_CONFIG_FILE"
fi

hostPathToServerPath () {
	local hostPath="$1"
	local projectRoot="${PROJECT_ROOT%/}"
	local serverRoot="${SERVER_PROJECT_ROOT:-${SERVER_BASE_FOLDER:-}}"
	serverRoot="${serverRoot%/}"

	if [[ -z "$serverRoot" ]]; then
		printf '%s\n' "$hostPath"
		return 0
	fi

	if [[ "$hostPath" == "$projectRoot" ]]; then
		printf '%s\n' "$serverRoot"
	elif [[ "$hostPath" == "$projectRoot/"* ]]; then
		printf '%s/%s\n' "$serverRoot" "${hostPath#$projectRoot/}"
	else
		printf '%s\n' "$hostPath"
	fi
}

projectStructure_hostPathToServerPath () {
	hostPathToServerPath "$@"
}

projectStructure_defineServerPaths () {
	return 0
}

# declare -rx SERVER_SCRIPT_FOLDER="$(hostPathToServerPath $SCRIPT_FOLDER)"	# Folder containing the project scripts
# declare -rx SERVER_UTILITY_SCRIPT_FOLDER="$(hostPathToServerPath $UTILITY_SCRIPT_FOLDER)"	# Folder containing utility scripts
# declare -rx SERVER_PRJ_FOLDER="$(hostPathToServerPath $PRJ_FOLDER)"	# Folder contianning the .prj file containing all SystemVerilog file paths to all modules needed for the MODULE_NAME simulation
# declare -rx SERVER_SIM_FOLDER="$(hostPathToServerPath $SIM_FOLDER)"	# Main folder for simulation (using Verilator)
# declare -rx SERVER_SIM_LOG_FOLDER="$(hostPathToServerPath $SIM_LOG_FOLDER)"	# Folder for simulation logs
# declare -rx SERVER_VECTOR_FOLDER="$(hostPathToServerPath $VECTOR_FOLDER)"	# Folder for input/output vector files are stored, from GoldenModel and Verilator simulation
# declare -rx SERVER_BUILD_FOLDER="$(hostPathToServerPath $BUILD_FOLDER)"	# Folder for Verilator executable will be built
# declare -rx SERVER_EXEC_FOLDER="$(hostPathToServerPath $EXEC_FOLDER)"	# Folder for GoldenModel (and possibly other programs used for simulation) executable will be stored
# declare -rx SERVER_RTL_FOLDER="$(hostPathToServerPath $RTL_FOLDER)"	# 
# declare -rx SERVER_TB_FOLDER="$(hostPathToServerPath $TB_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FOLDER="$(hostPathToServerPath $SYNTH_FOLDER)"	# General folder for Synthesis				
# declare -rx SERVER_SYNTH_ASIC_LOG_FOLDER="$(hostPathToServerPath $SYNTH_ASIC_LOG_FOLDER)"	# 
# declare -rx SERVER_SYNTH_ASIC_NETLIST_FOLDER="$(hostPathToServerPath $SYNTH_ASIC_NETLIST_FOLDER)"	# 
# declare -rx SERVER_SYNTH_ASIC_REPORT_FOLDER="$(hostPathToServerPath $SYNTH_ASIC_REPORT_FOLDER)"	# 
# declare -rx SERVER_SYNTH_ASIC_SCRIPTS_FOLDER="$(hostPathToServerPath $SYNTH_ASIC_SCRIPTS_FOLDER)"	# 
# declare -rx SERVER_SYNTH_ASIC_WORK_FOLDER="$(hostPathToServerPath $SYNTH_ASIC_WORK_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FPGA_LOGS_FOLDER="$(hostPathToServerPath $SYNTH_FPGA_LOGS_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FPGA_NETLIST_FOLDER="$(hostPathToServerPath $SYNTH_FPGA_NETLIST_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FPGA_REPORTS_FOLDER="$(hostPathToServerPath $SYNTH_FPGA_REPORTS_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FPGA_SCRIPTS_FOLDER="$(hostPathToServerPath $SYNTH_FPGA_SCRIPTS_FOLDER)"	# 
# declare -rx SERVER_SYNTH_FPGA_WORK_FOLDER="$(hostPathToServerPath $SYNTH_FPGA_WORK_FOLDER)"	#
# declare -rx SERVER_SCRIPT_RUN_SYNTH_ASIC="$(hostPathToServerPath $SCRIPT_RUN_SYNTH_ASIC)"	#
# declare -rx SERVER_TCL_SCRIPT_SYNTH_ASIC="$(hostPathToServerPath $TCL_SCRIPT_SYNTH_ASIC)"	#
# declare -rx SERVER_LOG_SYNTH_ASIC="$(hostPathToServerPath $LOG_SYNTH_ASIC)"			#
# declare -rx SERVER_GOLDEN_FOLDER="$(hostPathToServerPath $GOLDEN_FOLDER)"			# Folder for Golden Model source code is stored
# declare -rx SERVER_GOLDEN_SIM_MAIN="$(hostPathToServerPath $GOLDEN_SIM_MAIN)"		# Main source file used to compile the Golden Model for simulation
# declare -rx SERVER_GOLDEN_NIST_MAIN="$(hostPathToServerPath $GOLDEN_NIST_MAIN)"		# Main source file used to compile the Golden Model for NIST tests
# declare -rx SERVER_GOLDEN_SIM_SRC="$(hostPathToServerPath $GOLDEN_SIM_SRC)"		# Full path of the simulation Golden Model main source file
# declare -rx SERVER_GOLDEN_NIST_SRC="$(hostPathToServerPath $GOLDEN_NIST_SRC)"		# Full path of the NIST Golden Model main source file
# declare -rx SERVER_PRJ_FILE_SIM="$(hostPathToServerPath $PRJ_FILE_SIM)"			# File containing the list of all SystemVerilog files needed for the simulation (contains the paths to TB files)
# declare -rx SERVER_PRJ_FILE_SYNTH_ASIC="$(hostPathToServerPath $PRJ_FILE_SYNTH_ASIC)"	# File containing the list of all SystemVerilog files needed for ASIC synthesis
# declare -rx SERVER_PRJ_FILE_SYNTH_FPGA="$(hostPathToServerPath $PRJ_FILE_SYNTH_FPGA)"	# File containing the list of all SystemVerilog files needed for FPGA synthesis
# declare -rx SERVER_ABS_PRJ_FILE="$(hostPathToServerPath $ABS_PRJ_FILE)"			# File containing the list of all SystemVerilog files needed for the simulation in absolute path format
# declare -rx SERVER_TMP_ABS_PRJ_FILE="$(hostPathToServerPath $TMP_ABS_PRJ_FILE)"		# Temporary file used to update ABS_PRJ_FILE only when content changes
# declare -rx SERVER_SIM_SCRIPT_LOG="$(hostPathToServerPath $SIM_SCRIPT_LOG)"			# File where the simulation script terminal dump is stored
# declare -rx SERVER_SIM_GOLDENMODEL_LOG="$(hostPathToServerPath $SIM_GOLDENMODEL_LOG)"	# File where the simulation Golden Model build log is stored
# declare -rx SERVER_SIM_VERILATOR_LOG="$(hostPathToServerPath $SIM_VERILATOR_LOG)"		# File where the Verilator build log is stored
# declare -rx SERVER_GOLDEN_MAKEFILE="$(hostPathToServerPath $GOLDEN_MAKEFILE)"		# Makefile used to compile the Golden Model
# declare -rx SERVER_GOLDEN_EXE="$(hostPathToServerPath $GOLDEN_EXE)"			# Name of the Golden Model executable 
# declare -rx SERVER_SIM_EXE_NAME="$(hostPathToServerPath $SIM_EXE_NAME)"			# Name of the Verilator simulation executable
# declare -rx SERVER_SIM_EXE_PATH="$(hostPathToServerPath $SIM_EXE_PATH)"			# Path of the Verilator simulation executable
# declare -rx SERVER_INPUT_VECTOR_FILE="$(hostPathToServerPath $INPUT_VECTOR_FILE)"	# Input vector file generated by the Golden Model
# declare -rx SERVER_OUTPUT_VECTOR_FILE="$(hostPathToServerPath $OUTPUT_VECTOR_FILE)"		# Output vector file generated by the Golden Model
# declare -rx SERVER_HDL_OUTPUT_FILE="$(hostPathToServerPath $HDL_OUTPUT_FILE)"			# Output vector file generated by the HDL (Verilator) simulation
# declare -rx SERVER_VCD_FILE="$(hostPathToServerPath $VCD_FILE)"				# VCD file generated by the Verilator simulation
# declare -rx SERVER_NIST_Suite_Folder="$(hostPathToServerPath $NIST_Suite_Folder)"		# Main NIST Test Directory
# declare -rx SERVER_NIST_stsFolder="$(hostPathToServerPath $NIST_stsFolder)"		# Folder containing the NIST STS makefile and executable
# declare -rx SERVER_NIST_MyFolder="$(hostPathToServerPath $NIST_MyFolder)"			# 
# declare -rx SERVER_NIST_testFolder="$(hostPathToServerPath $NIST_testFolder)"			# Folder containing files used by NIST tests for the selected module
# declare -rx SERVER_NIST_testConfig="$(hostPathToServerPath $NIST_testConfig)"			# File containing the answers for the NIST interactive menu
# declare -rx SERVER_NIST_inputFile="$(hostPathToServerPath $NIST_inputFile)"			# 
# declare -rx SERVER_NIST_resultFolder="$(hostPathToServerPath $NIST_resultFolder)"		# Folder containing NIST result reports
# declare -rx SERVER_NIST_finalAnalysisReport="$(hostPathToServerPath $NIST_finalAnalysisReport)"	# Final report generated by the NIST suite
# declare -rx SERVER_NIST_plotFolder="$(hostPathToServerPath $NIST_plotFolder)"				# Folder containing plots generated from NIST results
# declare -rx SERVER_NIST_totalPassRatePlot="$(hostPathToServerPath $NIST_totalPassRatePlot)"		# Plot showing the total pass rate for every NIST test
# declare -rx SERVER_NIST_uniformityPlotFolder="$(hostPathToServerPath $NIST_uniformityPlotFolder)"	# Folder containing p-value uniformity histograms
# declare -rx SERVER_NIST_uniformitySummaryFile="$(hostPathToServerPath $NIST_uniformitySummaryFile)"	#V summary for p-value uniformity checks
# declare -rx SERVER_SCRIPT_NIST_setup="$(hostPathToServerPath $SCRIPT_NIST_setup)"			# NIST Setup Script
# declare -rx SERVER_SCRIPT_NIST_runTest="$(hostPathToServerPath $SCRIPT_NIST_runTest)"			# NIST Test executable
# declare -rx SERVER_SCRIPT_NIST_plotResults="$(hostPathToServerPath $SCRIPT_NIST_plotResults)"		# Python script used to plot NIST results
# declare -rx SERVER_BASH_LIB_FOLDER="$(hostPathToServerPath $BASH_LIB_FOLDER)"		# 
# declare -rx SERVER_BASH_LIB_GENERAL="$(hostPathToServerPath $BASH_LIB_GENERAL)"		# 
# declare -rx SERVER_BASH_LIB_SERVER="$(hostPathToServerPath $BASH_LIB_SERVER)"		# 
# declare -rx SERVER_SERVER_CONFIG_FILE="$(hostPathToServerPath $SERVER_CONFIG_FILE)"		# 
# declare -rx SERVER_SCRIPT_SERVER_CONFIG="$(hostPathToServerPath $SCRIPT_SERVER_CONFIG)"	# 
# declare -rx SERVER_REPORT_SYNTH_ASIC_TIMING="$(hostPathToServerPath $REPORT_SYNTH_ASIC_TIMING)"
# declare -rx SERVER_REPORT_SYNTH_ASIC_AREA="$(hostPathToServerPath $REPORT_SYNTH_ASIC_AREA)"
# declare -rx SERVER_SDF_SYNTH_ASIC="$(hostPathToServerPath $SDF_SYNTH_ASIC)"
# declare -rx SERVER_NETLIST_SYNTH_ASIC="$(hostPathToServerPath $NETLIST_SYNTH_ASIC)"
# declare -rx SERVER_SDC_SYNTH_ASIC="$(hostPathToServerPath $SDC_SYNTH_ASIC)"

declare -rx SERVER_SCRIPT_SYNTH_ASIC_INIT="${SERVER_SCRIPT_SYNTH_ASIC_INIT:-/path/to/remote/server/init_design_compiler}"
declare -rx SERVER_SCRIPT_SYNTH_FPGA_INIT="${SERVER_SCRIPT_SYNTH_FPGA_INIT:-/path/to/remote/server/init_vivado}"
declare -x SERVER_BASE_FOLDER="${SERVER_BASE_FOLDER:-$DEFAULT_SERVER_BASE_FOLDER}"
