#!/usr/bin/env bash

# ==============================================================================================
# Project: PEARL -- PRNG Evaluation for Area, Randomness, and Leakage
# Authors: Valeria Piscopo, Alessandra Dolmeta (EDGE Group, VLSI Lab, Dept. of Electronics and Telecommunications, Politecnico di Torino);
#          Behnam Farnaghinejad (Dept. of Control and Computer Engineering, Politecnico di Torino)
# ----------------------------------------------------------------------------------------------

set -e				# Fail if any command exits with an error
set -u				# Fail if an undefined variable is used
set -o pipefail		# Fail a pipeline if any command inside it fails

PROJECT_ROOT=$(realpath "$(dirname "${BASH_SOURCE[0]}")/../..")

source "${PROJECT_ROOT}/scripts/utility_scripts/projectStructure.sh"

# Create the configuration directory if it does not exist
mkdir -p "$CONFIG_DIR"

echo "========================================================"
echo "---------------- Server configuration ------------------"

# Check if the configuration file already exist, and if exists ask the user if he wants to overwrite it
if [[ -f "$SERVER_CONFIG_FILE" ]]; then
	read -r -p "Config already exists. Overwrite it? [y/N]: " choice
	case "$choice" in
		y|Y|yes|YES) ;;
		*)
			echo "Keeping existing config."
			exit 0
			;;
	esac
fi

# Ask the user to provide all the data about the Server he wants to connect to
read -r -p "Server user: " SERVER_USER_VALUE
read -r -p "Server host: " SERVER_HOST_VALUE
read -r -p "Server SSH port: " SERVER_PORT_VALUE
read -r -p "Server project base folder [$DEFAULT_SERVER_BASE_FOLDER]: " SERVER_BASE_FOLDER_VALUE
read -r -p "Project SSH key name (no spaces, this is just to recognise this key from others in your PC): " SERVER_PROJECT_NAME_VALUE

SERVER_BASE_FOLDER_VALUE="${SERVER_BASE_FOLDER_VALUE:-$DEFAULT_SERVER_BASE_FOLDER}"

# Define the file path where to save the Public and Private Keys for the SSH connection to the server
SERVER_SSH_KEY_VALUE="$HOME/.ssh/${SERVER_PROJECT_NAME_VALUE}_key"

# Check if all the Required fields where inserted by the User
if [[ -z "$SERVER_USER_VALUE" || -z "$SERVER_HOST_VALUE" || -z "$SERVER_PORT_VALUE" || -z "$SERVER_BASE_FOLDER_VALUE" || -z "$SERVER_PROJECT_NAME_VALUE" ]]; then
	echo "ERROR: all fields are required." >&2
	exit 1
fi

# Check if the PROJECT_NAME has spaces. Because it is used in a "path" it can not have any spaces
if [[ "$SERVER_PROJECT_NAME_VALUE" == *" "* ]]; then
	echo "ERROR: project SSH key name cannot contain spaces." >&2
	exit 1
fi

# Write the Config File for the Server with all the necessary informations to connect to the server
echo "# Local server configuration." > "$SERVER_CONFIG_FILE"
echo "# This file is generated by scripts/setup_server_config.sh and ignored by git." >> "$SERVER_CONFIG_FILE"
echo "" >> "$SERVER_CONFIG_FILE"
echo "SERVER_USER=\"$SERVER_USER_VALUE\"" >> "$SERVER_CONFIG_FILE"
echo "SERVER_HOST=\"$SERVER_HOST_VALUE\"" >> "$SERVER_CONFIG_FILE"
echo "SERVER_PORT=\"$SERVER_PORT_VALUE\"" >> "$SERVER_CONFIG_FILE"
echo "SERVER_BASE_FOLDER=\"$SERVER_BASE_FOLDER_VALUE\"" >> "$SERVER_CONFIG_FILE"
echo "SERVER_PROJECT_NAME=\"$SERVER_PROJECT_NAME_VALUE\"" >> "$SERVER_CONFIG_FILE"
echo "SERVER_SSH_KEY=\"$SERVER_SSH_KEY_VALUE\"" >> "$SERVER_CONFIG_FILE"

# Remove permission to read/write/access this file to other users than the proprietary
chmod 600 "$SERVER_CONFIG_FILE"

echo
echo " Server config written to: $SERVER_CONFIG_FILE"
echo

# Setup the Keys to access the Server without the need to insert the password everytime
read -r -p "Setup SSH key access now? [y/N]: " setup_ssh
case "$setup_ssh" in
	y|Y|yes|YES)
		mkdir -p "$HOME/.ssh"	# Create the folder where Keys will be stored in the Host PC
		chmod 700 "$HOME/.ssh"	# Remove permission to read/write/access this file to other users than the proprietary

		# Generate a new SSH key pair:
		#	- private key: stays only on this PC and is used to prove your identity
		#	- public key: can be copied to the server to allow passwordless login ssh-keygen options used here:
		#	- -t rsa: choose RSA as key type
		#	- -b 4096: create a 4096-bit key, stronger than the old default RSA size
		#	- -C: add a comment/label to recognise this key later
		#	- -f: choose where to save the private key file
		#	- -N "": use an empty passphrase, so scripts can use the key without asking one
		ssh-keygen -t rsa -b 4096 -C "$SERVER_PROJECT_NAME_VALUE" -f "$SERVER_SSH_KEY_VALUE" -N ""

		# Copy the public key to the server user account:
		#	- -i: choose which public key file must be installed on the server
		#	- -p: choose the SSH port used by the server
		# After this, the server can recognise the private key stored on this PC.
		ssh-copy-id -i "$SERVER_SSH_KEY_VALUE.pub" -p "$SERVER_PORT_VALUE" "$SERVER_USER_VALUE@$SERVER_HOST_VALUE"
		;;
	*)
		echo "Skipping SSH key setup."
		echo "You can run ssh-copy-id later using:"
		echo "ssh-copy-id -i \"$SERVER_SSH_KEY_VALUE.pub\" -p \"$SERVER_PORT_VALUE\" \"$SERVER_USER_VALUE@$SERVER_HOST_VALUE\""
		;;
esac
